server:
  port: 8086

spring:
  application:
    name: frontend-service

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          keycloak-user-service:
            client-id: ${user-service.name}
            client-secret: SlDu0pPghNiAJ2zo4UzHsp7zy1DVUvbp
            authorization-grant-type: client_credentials
            provider: keycloak
          keycloak-product-service:
            client-id: ${product-service.name}
            client-secret: sWdHyl6nx6kKw2WkM6jIf66z2nmgEpos
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/e-commerce-platform/protocol/openid-connect/token

  rabbitmq:
    host: localhost
    topicExchange: e-commerce-platform-order-service-exchange
    queues:
      order-create: order.create.queue
      order-update: order.update.queue
      order-change-status: order.change-status.queue
      order-delete: order.delete.queue

dummy-repositories:
  enabled: true

user-service:
  enabled: false
  name: user-service
  url: http://localhost:8081/api/v1/users

product-service:
  enabled: false
  name: product-service
  url: http://localhost:8082/api/v1/products

order-service:
  enabled: true
  graphql-url: http://localhost:8083/graphql