server:
  port: 8083

spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/e-commerce-platform-order-service

  graphql:
    graphiql:
      enabled: true

  rabbitmq:
    host: localhost
    topicExchange: e-commerce-platform-order-service-exchange
    queues:
      order-create: order.create.queue
      order-update: order.update.queue
      order-change-status: order.change-status.queue
      order-delete: order.delete.queue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
