# Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  labels:
    app: e-commerce-platform-rabbitmq
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rabbitmq"  # This path is on the host node's file system

---
# Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  labels:
    app: e-commerce-platform-rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# RabbitMQ Deployment
apiVersion : apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: e-commerce-platform-rabbitmq
spec:
  replicas: 1 #2
  selector:
    matchLabels:
      project: e-commerce-platform-rabbitmq
  template:
    metadata:
      labels:
        project: e-commerce-platform-rabbitmq
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:latest
        ports:
          - containerPort: 5672
            name: rmq-amqp
          - containerPort: 15672
            name: rmq-management
        volumeMounts:
          - mountPath: /var/lib/rabbitmq  # RabbitMQ data directory
            name: rabbitmq-storage
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

---
# RabbitMQ Service
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
     env  : dev
     owner: IvanGorbunov
spec:
  selector:
    project: e-commerce-platform-rabbitmq
  ports:
    - name: rabbitmq-amqp-listener
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-management-listener
      protocol: TCP
      port: 15672
      targetPort: 15672
  #type: CLusterIP
