apiVersion : apps/v1
kind: Deployment
metadata:
  name: review-service-deployment
  labels:
    app: e-commerce-platform-review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      project: e-commerce-platform-review-service
  template:
    metadata:
      labels:
        project: e-commerce-platform-review-service
    spec:
      containers:
        - name: review-service
          image: ivangorbunovv/e-commerce-platform:review-service
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_APPLICATION_JSON
              value: >
                {
                 "spring.config.import" : "configserver:http://config-server:8888"
                }

---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  labels:
     env  : dev
     owner: IvanGorbunov
spec:
  selector:
    project: e-commerce-platform-review-service
  ports:
    - name      : review-service-listener
      protocol  : TCP
      port      : 8084
      targetPort: 8084
  #type: CLusterIP