services:

  #  Kafka
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka

  #  RabbitMQ
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5673:5672"  # RabbitMQ port
      - "15673:15672"  # RabbitMQ management UI port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # Localhost - we need it to enabled seamless communication between Frontend-service and Keycloak
  localhost:
    image: alpine:latest
    command: sleep infinity
    ports:
      - "8080:8080" # Keycloak port
      - "8086:8086" # Frontend-service port

  #  Keycloak
  keycloak:
    depends_on:
      - localhost
    image: quay.io/keycloak/keycloak:latest
#    ports:
#      - "8080:8080" # Commented out because ports are bound via the "localhost" service
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    network_mode: "service:localhost"
    volumes:
      - keycloak_data:/opt/keycloak/data

  #  Config-server
  config-server:
    image: ivangorbunovv/config-server-e-commerce-platform-image
    ports:
      - "8888:8888"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.cloud.config.server.git.uri" : "https://github.com/GorbunovIvan/config-repo-e-commerce-platform.git",
          "spring.cloud.config.server.git.username" : "GorbunovIvan",
          "spring.cloud.config.server.git.password" : "246aintzZ",
          "spring.cloud.config.server.git.default-label" : "main"
      }'

  #  Eureka-server
  eureka-server:
    depends_on:
      - config-server
    image: ivangorbunovv/eureka-server-e-commerce-platform-image
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.config.import" : "configserver:http://config-server:8888"
      }'

  #  Api-gateway
  api-gateway:
    depends_on:
      - config-server
      - eureka-server
    image: ivangorbunovv/api-gateway-e-commerce-platform-image
    ports:
      - "8765:8765"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.config.import" : "configserver:http://config-server:8888"
      }'

  #  This app (frontend-service)
  frontend-service:
    depends_on:
      - localhost
      - keycloak
      - kafka
      - rabbitmq
      - config-server
      - eureka-server
    image: ivangorbunovv/frontend-service-e-commerce-platform-image
#    ports:
#      - "8086:8086" # Commented out because ports are bound via the "localhost" service
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.config.import" : "configserver:http://config-server:8888"
      }'
    network_mode: "service:localhost"

volumes:
  kafka-data:
    driver: local
  rabbitmq-data:
    driver: local
  keycloak_data:
    driver: local
